//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCafeDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string employeeName { get; set; }
        public System.DateTime birthday { get; set; }
        public System.DateTime hireDay { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string number { get; set; }
        public bool isManager { get; set; }
        public Nullable<int> shiftId { get; set; }
        public bool isFired { get; set; }
        public bool status { get; set; }
    
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public override string ToString()
        {
            return id.ToString()+" - "+employeeName.ToString();
        }
    }
}
